services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FABRIC
      MODS_FILE:/extras/mods.txt
      REMOVE_OLD_MODS: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt:ro
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}